Código da Equipe: EQ01
Componentes:
	Patrick Guilherme da Silva; patrick.silva@aln.senaicimatec.edu.br; (71) 99945-8148
	Guilherme Garcia Oliveira; guilherme.g.oliveira@aln.senaicimatec.edu.br; (71) 98134-0749
	Victor Lima Conceição; victor.Conceicao@aln.senaicimatec.edu.br; (71) 98600-1311
	Igor Cunha Lobato Souza; igor@aln.senaicimatec.edu.br; (71) 99147-4206

RELATÓRIO DA TABELA DE SIMBOLOS. Texto fonte analisado: teste
---------------------------------------------------------------------------------------------------------
Entrada: 1, Codigo: C01, Lexeme: nomeCADEIA 
QtdCharAntesTrunc:  10, QtdCharDepoisTrunc:  10 
TipoSimb: consCadeia, Linhas [ 0,]
---------------------------------------------------------------------------------------------------------
Entrada: 1, Codigo: C01, Lexeme: nome cadeia 
QtdCharAntesTrunc:  11, QtdCharDepoisTrunc:  11 
TipoSimb: consCadeia, Linhas [ 0,]
---------------------------------------------------------------------------------------------------------
Entrada: 1, Codigo: C01, Lexeme: nome $cadeia 
QtdCharAntesTrunc:  12, QtdCharDepoisTrunc:  12 
TipoSimb: consCadeia, Linhas [ 0,]
---------------------------------------------------------------------------------------------------------
