Código da Equipe: EQ01
Componentes:
	Patrick Guilherme da Silva; patrick.silva@aln.senaicimatec.edu.br; (71) 99945-8148
	Guilherme Garcia Oliveira; guilherme.g.oliveira@aln.senaicimatec.edu.br; (71) 98134-0749
	Victor Lima Conceição; victor.Conceicao@aln.senaicimatec.edu.br; (71) 98600-1311
	Igor Cunha Lobato Souza; igor@aln.senaicimatec.edu.br; (71) 99147-4206

RELATÓRIO DE ANÁLISE LÉXICA. Texto fonte analisado: TESTE
---------------------------------------------------------------------------------------------------------
